name: run api tests

on:
  push:
    branches: 
      'features-mix/*'
      
      
jobs:
  run-api-test:
    runs-on: linux-vv
      
steps:
  - name: Checkout
    uses: actions/checkout@v3.5.3
    
  - name: api-test
    run: builder-api
