name: api test

on:
  push:
    branches: 
      'api/*'
      
jobs:
  run-api-test:
    runs-on: linux-vv
    
    steps:
      - name: Checkout
        uses: actions/checkout@v3.5.3
        
      - name: run-api
        run: api
  
